### PR TITLE
add handler package

### PR DESCRIPTION
**Pull request by cheikhshift**
Move source code suffixed with Handler to package handler.

## Description
Add a new sub-level package.

## Motivation and Context

It creates a new package to isolate derek api functionality. This is to move closer towards deploying derek as a function.

- [ ] I have raised an issue to propose this change ([required](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

I refactored a local instance of the project to use package `handler`. I also added a local FaaS function to test the Handler package with.

I used faas-cli 0.7.7 to build and deploy the function.

This will require updating [main.go](https://github.com/alexellis/derek/blob/master/main.go) to use the handler package.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for this PR. Looks like the 2nd commit is missing the signed-off-by line/flag. 

Also think you'll need to update references in the main.go to use the new `handler` package. 

For example

`handleComment` needs to become `HandleComment` so it is visible outside the handler package via the `main` package such as `handler.HandleComment()`.

I know I said about moving the these files in my comment on the issue, but I meant in a way that works/compiles/passes the build.

**Comment by cheikhshift** [comment]
Sure.

**Comment by alexellis** [comment]
I'm heading off for today. It would be good to get the commits squashed down into one before review. Thanks for getting involved :+1:

**Comment by alexellis** [comment]
@rgee0 I think this can be merged, do you have any input?

**Comment by alexellis** [comment]
@cheikhshift I think for the next part this unfortunately means the function will vendor the same GitHub repo it lives in which makes it a bit of a challenge to test/release changes. Any other ideas for this?

**Comment by cheikhshift** [comment]
None as of now. 

The quick solution I used during development was to have a separate vendor folder within the function's folder. I'll learn more about the FaaS build command to see if there is a better/reliable way.

**Comment by cheikhshift** [comment]
Would it be possible to add a function sub package to this repository?

**Pull request merged**
