### PR TITLE
Support the loading of config files via URL redirection

### PR DESCRIPTION
**Pull request by neolit123**
## Description

this PR adds support for the optional `redirect` filed in `.DEREK.yaml` to allow jumping away from this config and loading another. the change is non-breaking for existing users.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md))

spoke to @alexellis about this at KubeCon. :)
the idea is to allow multiple repos to use the same config file.

https://github.com/alexellis/derek/issues/58

## How Has This Been Tested?

pushed a test config to a github fork and added a temporary test in `permissionsHandler_test.go` (not included) that fetches the config from a redirected URL. then did a `go fmt`, `golint` and `go test -v` on the changes.

the best way to test this is to pull this branch and add this in the yaml:
```
redirect: <some-config-url>
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Lubomir - awesome to see that you've got straight onto this!

I'll ping @rgee0 who helps me maintain Derek for feedback.

Richard - this is a feature you, @johnmccabe or @iyovcheva  suggested. WDYT?

Alex

**Comment by alexellis** [comment]
Issue #58 raised to cover this

**Comment by alexellis** [comment]
It doesn't seem like we've had a response from the people I pinged. I'll do the review myself.

@neolit123 please could you work with @iyovcheva to set up your own Derek app to test the change?

Instructions are in DEV.md - you have to set up a "GitHub App" - export the private key - initialize Docker Swarm - Deploy OpenFaaS - create the secret and then with the private key then run ngrok or some NAT solution - take the IP / port combination and put it into the web-hook page of your GitHub App.

**Comment by rgee0** [comment]
While it is a closed system you can be (relatively) sure that the maintainers file is reachable.  If the system ceases to be closed how is an absence of accessibility to the maintainers file going to be handled so that it doesn't reflect on Derek and remains in a supportable state?

**Comment by neolit123** [comment]
@rgee0 @alexellis 

so right now we `Exit(1)` which is called from any `log.Fatalln` and that was part of the original logic.

we could potentially do a couple of things as a start:
1) don't terminate the process on errors - i.e. don't call `log.Fatalln`?
2) if the config to which we redirected is non-parsable or non-loadable fall back to the origin config?

**Comment by rgee0** [comment]
Another approach might be to restrict the redirect url to somewhere else on github.  The idea originated from the project having to keep `.DEREK.yml` up to date across multiple github repos.

Security of `.DEREK.yml` would then be built in too.

**Comment by neolit123** [comment]
> Another approach might be to restrict the redirect url to somewhere else on github.

sounds good.
how about the validation of that? are we still going to use `log.Fatalln` if the URL doesn't match the `github.com` pattern.

**Comment by rgee0** [comment]
Thats a good question.  Since the redirect is a project configuration item, rather than a system/hosting configuration, how does the fact that the redirect is invalid get fed back to the project if they cant see the logs?  

Could Derek could post back to the comments of the issue being acted upon that the redirect is invalid? Not sure how that scales though.

@alexellis any thoughts?

**Comment by alexellis** [comment]
> in terms of the bot posting logs in the comments, i have to admit that i'm not a big fan of that even if it can be very useful in terms of visibility.

I agree on this topic - we need a good way to monitor Derek's health #36 and have observability.  

If we commented/replied on every action whether positive/negative it'd be too easy to abuse the system and use up the rate limit per hour.

Let's move this PR forward since we don't have any visibility if the .DEREK.yml file is invalid or non-existing anyway without a redirect.

**Comment by neolit123** [comment]
> Let's move this PR forward since we don't have any visibility if the .DEREK.yml file is invalid or non-existing anyway without a redirect.

should i at least add the suggestion by @rgee0 to only redirect to the `github` domain. i wonder if users might want to store that config on a remote machine instead of always on github.

**Comment by alexellis** [comment]
We support sourcing from the GitHub repo that originated the event, so keeping to GitHub I think is fair as a requirement. It's OK to be opinionated about this since we are offering a redirect to another repository rather than any arbitrary site.

**Comment by neolit123** [comment]
sounds good, i will append this later today.

**Comment by neolit123** [comment]
pushed updates with the github validation also added a test and bumped the readme.
let me know if you think something can be changed in the URL / domain validation. :+1:

**Comment by johnmccabe** [comment]
I would be inclined to restrict this to an org - ie you would supply only the `repo/file` rather than a url - with derek automatically prepending the org.

**Comment by alexellis** [comment]
LGTM - I can confirm from testing that Derek works with redirect. Thank you for the contribution @neolit123 Extra points for the unit tests :100:

**Comment by alexellis** [comment]
@johnmccabe happy to take a follow-up PR / issue for the suggestion.

**Pull request merged**
