### PR TITLE
Added my GitHub user name per the Get Derek instructions.

### PR DESCRIPTION
**Pull request by colin-mccarthy**
Signed-off-by: colin-mccarthy <colin@colin.mccarthy80501@gmail.com>

## Description

I have added my GitHub user name per the Get Derek instructions. I am excited to use Derek on my 
repo.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Colin, your sign-on email is invalid. Please can you fix it?

Alex

**Comment by alexellis** [comment]
Please run:

```sh
git config --global user.name "Colin McCarthy"
git config --global user.email "colin.mccarthy80501@gmail.com"

git commit -s --amend --reset-author
git push origin master --force
```

**Comment by colin-mccarthy** [comment]
Okay, I have fixed it. Thanks for the help!

**Comment by alexellis** [comment]
Merged. Please see the readme on how to proceed and let me know if you run into any issues. Alex

**Pull request merged**
