### PR TITLE
[Blocked] Add Slack Notification Support

### PR DESCRIPTION
**Pull request by shawncarr**
Signed-off-by: Shawn Carr <shawn@sharpnotions.com>

## Description

Changes to attempt to fulfill proposal in issue #36.  This is my first time with golang so I am unsure if I followed the code style of this project but golint didn't see a problem with my code. That said while I believe did this correctly I could be completely wrong.

The one area that was unsure about was the configuration for Slack. I added a feature flag for slack but need to have more settings than what the features of `.DEREK.yml` could support with non-breaking changes to that file. To that end I added a Slack settings struct that allowed the settings to be added outside of the features. Also I opted for applying the settings via `setSlackSettings(derekConfig)` after the `derekConfig` had been loaded in the `main.go`. I did this so that existing function signatures did not have to be updated with `derekConfig` being passed along then causing repeating logic.

One area of improvement could have been to include the url of the issue or PR in the messages so that in Slack you could click on the link and go right to the issue or PR. 

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md))
I wanted to see if I could program in Go so I used issue #36 as an attempt.

## How Has This Been Tested?

Added unit tests to test different scenarios of sending a message to Slack.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Shawn,

Thanks for contacting me on Twitter about this PR. 

Before going any further I wanted to link you to this and get your thoughts. https://api.slack.com/docs/oauth-safety#custom_integrations

Thanks,

Alex

**Comment by shawncarr** [comment]
I completely agree with them on not storing in a public repo. 

But it was basic catch 22. If the webhook was not stored in the `.DEREK.yml` and hosted in secrets or via environment variables then it becomes only notifications for the hoster of Derek which then defeated the purpose of this integration in my mind at least.

Shawn

**Comment by alexellis** [comment]
As the operator of a shared Derek SaaS I want to be able to check usage - actions that pass and those that fail. 

It's the point of the feature - I explain in the original ticket that the data is public so I don't see any issues with the host receiving the metrics.

**Comment by shawncarr** [comment]
Sorry I misread the intent of the feature. 

Then yes I would change all of the settings to environmental variables to be implemented by the operator so that it customizable at that level. If the slack webhook is not present then it would skip sending.

**Comment by alexellis** [comment]
Hi it looks like a few things need doing in addition to revisiting the design/approach. 

Rebase is needed with master (not a merge)
Commits need signing-off
Commit messages don’t follow contribution guide and should do

It may also make sense to pause and review how many pings will come through via Slack and which the operator cares about.

**Comment by alexellis** [comment]
Hi Shawn,

To make use of your work it would help if you could you sign-off the commits and rebase?

We also have some other open issues where help is wanted. 

Thanks,

Alex

**Comment by alexellis** [comment]
Title is now "blocked" pending above.

**Comment by shawncarr** [comment]
Sorry, @alexellis didn't see the notifications for this project as they most likely got buried with other Github emails.

- [x] Rebased from upstream master 
- [x] Fixed Commit Messages (sorry used a client's contribution guide rules)
- [x] Fixed Commit with missing sign off

Was unsure how you wanted to handle 
> It may also make sense to pause and review how many pings will come through via Slack and which the operator cares about.

So I didn't change anything in that regard.

**Pull request closed without merging**
