### PR TITLE
Use repo default branch

### LINKED ISSUE #168: Detect repository default branch
## Expected Behaviour
I expect derek to look for its configuration file on the default branch of the repository instead of `master`.
GitHub changed its default branch from `master` to `main`, it is difficult to debug this issue if you don't run derek self-hosted.

## Current Behaviour
derek looks for the `.DEREK.yml` file in the root of the project in the `master` branch.

## Possible Solution
Identify what is the default branch of the repository, then look for the configuration file on that branch.

## Steps to Reproduce (for bugs)
1. Create a new repository
2. Setup derek in the default branch
3. Create a GitHub issue on the new repository
4. Add a comment requesting derek to add a label

## Context
During some derek modifications, I found this issue. Thanks that I self-hosted it I was able to find the misconfiguration in my repository.

## Your Environment

- [ ] You're using the hosted Derek service

or

- [ ] You host your own OpenFaaS cluster with Derek installed
- [X] I deployed a copy of Derek in a simple container without openfaas.

### PR DESCRIPTION
**Pull request by jolheiser**
## Description

This PR resolves #168. GitHub sends a repository's default branch along with webhook payload, so this is fairly straightforward with a small refactor.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md))
- [x] I didn't raise an issue, this PR aims to resolve and existing issue. (#168)

## How Has This Been Tested?

This PR passes the `make test` step, however I have not yet tested a running Derek.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for sending a PR.

I just wanted to let you know that I can't merge the PR unless you've tested it end to end, because several end-users and projects rely on Derek being 100% functional.

> This PR passes the make test step, however I have not yet tested a running Derek.

What I'd like to see is Derek tested with a regular repository using master as the default branch, and whatever other use-case you had in mind, I assume it would be for the "main" branch?

Could you also verify with a public + private repo?

Setting up Derek is relatively quick and painless and we provide instructions in the docs, however GitHub Apps have a few steps you need to follow carefully. You can use inlets if you like, to get webhooks.

If you need any synchronous help - feel free to reach out on Slack in #general.

**Review by alexellis — CHANGES_REQUESTED** [review]
Thanks for submitting a PR. Due to the potential impact to active users and projects, end to end testing is required.

**Comment by alexellis** [comment]
@cpanato would you be interested in doing the testing here? IT seems like @jolheiser may have got too busy, or perhaps wasn't able to put in the time to test this change end to end?

**Comment by cpanato** [comment]
@alexellis I did an e2e test on my side (https://github.com/cpanato/testing-ghactions/pull/28) using a `master` branch and then change it to `main` for both public and private repo and works fine for me

I did the rebase of this PR, if you would like I can push it

**Comment by alexellis** [comment]
Sure, please push it up and start your own PR. Add the text `closes #171`

**Comment by cpanato** [comment]
I can push to this existing PR, so the contribution from the author will not get lost

**Comment by jolheiser** [comment]
Hello! 

Very sorry, I got busy and then it slipped my mind. I'm glad you were able to test it @cpanato, feel free to either push here or open your own. I have no qualms with either. 🙂 

Again, sorry I left this PR to languish!

**Comment by alexellis** [comment]
> I can push to this existing PR, so the contribution from the author will not get lost

No, that's not necessary or how attribution works (it's based upon commits, not PRs)

You can simply run `git commit -s --amend`, and it will credit you both.

Push up your own branch + PR and you will see.

**Comment by cpanato** [comment]
this PR can be closed in favor of https://github.com/alexellis/derek/pull/174

**Comment by jolheiser** [comment]
> this PR can be closed in favor of #174

Thanks again!

**Pull request closed without merging**
