### PR TITLE
Add contributing URL field to .DEREK.yml

### PR DESCRIPTION
**Pull request by viveksyngh**
This commit adds contributing_url field to the .DEREK.yml file to point
to contribution guide.

Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md))
Fixes: #87 

## How Has This Been Tested?

Test result and process added in comments below.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
LGTM. Can we find away to test it - or if that's too hard in the final method to figure out the URL outside and inject it then test that new method?

**Comment by viveksyngh** [comment]
I think we can write a method to figure out URL and test that method. I will try again to setup derek. Do you have any documentation for that?

**Comment by alexellis** [comment]
Documentation on how to write tests? There's lots of coverage in this project so I'd suggest copying the approach seen in another test file.

**Comment by alexellis** [comment]
Failing that ask on slack.

**Comment by viveksyngh** [comment]
Nope .. I was asking any documentation on how to setup derek ?

**Comment by viveksyngh** [comment]
Tested against this repo. https://github.com/viveksyngh/openfaas-functions for this PR https://github.com/viveksyngh/openfaas-functions/pull/3 using below derek configuration.

```yml
curators:
 - viveksyngh
 
features:
 - dco_check
 - comments

contributing_url: https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md
```

**Comment by viveksyngh** [comment]
@alexellis I have also added a new function which gets contributing URL and also added the unit test for that.

**Comment by alexellis** [comment]
Awesome 🎉 !

Glad you were able to test it end-to-end like this too. Did it help having worked with GitHub Apps in OpenFaaS Cloud?

**Comment by viveksyngh** [comment]
yeah .. that's for sure. It was really helpful.

**Comment by alexellis** [comment]
Derek add label: help wanted

**Comment by alexellis** [comment]
Derek remove label: help wanted

**Comment by alexellis** [comment]
I've released and deployed Derek 0.6.2, let's try it out?

* Update faas/.DEREK.yml to add the link (raise a PR) and I'll merge
* Find an openfaas repo that uses the redirect
* Raise a PR there without a DCO and check the link to the guide

**Pull request merged**
