### PR TITLE
Use repo default branch

### PR DESCRIPTION
**Pull request by cpanato**
## Description
Pushing and opening this PR to override the PR https://github.com/alexellis/derek/pull/171

For context see https://github.com/alexellis/derek/pull/171

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Tested deploying the Derek and configuring it.

- with private repo and public repo, using `master` branch as default and also using another branch name as default (in this case tested with `main` branch as default)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cpanato** [comment]
this PR just update the branch and there are no code changes.

@alexellis can you update the repo configuration to remove the status check for Travis and add the ones for GitHub action?
thanks!

**Comment by alexellis** [comment]
Please fix your commits for Derek - ideally rebase / squash them.

https://www.youtube.com/watch?v=8j0H6urZ-bU

**Comment by cpanato** [comment]
@alexellis done

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
Thanks for this.

Can you ping me when the Docker image is up? https://github.com/alexellis/derek/releases/tag/0.11.0 I'll deploy to the SaaS server then.

**Pull request merged**
