### PR TITLE
Add comma separated multi labels facility

### LINKED ISSUE #32: Posibility to pass multiple values to an action
It would be great to be able to send multiple values in the same action, i.e:

`Derek add label: UX, enhancement, proposal` (`,` as separator, more natural)
or
`Derek add label: UX || enhancement || proposal` (`||` as separator)

I can work on this if the proposal is accepted

### LINKED ISSUE #110: Proposal: support multiple commands in one comment
After reading the docs I got the impression I can specify multiple commands, so I added the following comment (on https://github.com/moby/moby/pull/38634):
```
d3r3k add label: rebuild/windowsRS1
d3r3k add label: rebuild/janky
```
... and nothing happened, so I figured I should start with a capital D, and edited the comment accordingly:

```
D3r3k add label: rebuild/windowsRS1
D3r3k add label: rebuild/janky
```

## Expected Behaviour

I expected two labels to be added.

## Current Behaviour

It added a single label "rebuild/windowsRS1
D3r3k add label: rebuild/janky" (yes, with a new line (aka carriage return, aka `\n`, aka `%0D`) in between).

I tried to remove it by using something like
```
D3r3k remove label: rebuild/windowsRS1
D3r3k add label: rebuild/janky
```
but it didn't work. It might be a bug in Github rather than Derek though )

## Proposed solution

I see a few possible ways to handle it:

* break input into sections starting with `^Derek[[:space:]]` regexp, and handle each one separately;
* discard anything after the first line, if the input is not supposed to be multiline (such as in case of labels);
* keep the current behavior, but document it ("only one command at a time") and change the examples accordingly.

### PR DESCRIPTION
**Pull request by rgee0**
Signed-off-by: Richard Gee <richard@technologee.co.uk>

## Description
This change enables multiple labels to be applied through a single comment, by allowing for a comma separated list to be provided.  Also added plural aliases for the labels commands.

This change also introduces a new env var which limits how many labels can be processed in a single command.  This defaults to 5 but can be set to preference through `multilabel_limit`.  An example has been included in the `stack.example.yml`. A test has been added for the function which retrieves this value from the env vars.

As the requested labels are pre-processed to ascertain which are actionable and which are not given the requested action, the limit will be applied to the first _n_ actionable labels, rather than the first _n_ requested labels.

As the deletion of multiple labels is currently an iterative process - due to how the GitHub API is presented - an error could occur mid-flow when deleting and cause subsequent labels to not be applied. Mitigation against this is that labels are visually verifiable.

## Motivation and Context
Currently to add multiple labels a maintainer must add one comment for each label.  Members have found this confusing with some calling the command multiple times per comment.

 [x] I have raised an issue to propose this change (fixes #32, closes #110 )

## How Has This Been Tested?
Unit tests added.
Built Derek at `rgee0/derek:multiLabels`
Deployed locally
Tested on test repo - https://github.com/rgee0/Test/issues/8

```
environment:
      application_id: 6184
      debug: true
      customers_url: https://raw.githubusercontent.com/alexellis/derek/master/.CUSTOMERS
      validate_hmac: false
      validate_customers: true
      secret_path: /var/openfaas/secrets/ # use /run/secrets/ for older OpenFaaS versions
```
image

```
environment:
      application_id: 6184
      multilabel_limit: 3
      debug: true
      customers_url: https://raw.githubusercontent.com/alexellis/derek/master/.CUSTOMERS
      validate_hmac: false
      validate_customers: true
      secret_path: /var/openfaas/secrets/ # use /run/secrets/ for older OpenFaaS versions
```
image

```
environment:
      application_id: 6184
      multilabel_limit: 3
      debug: true
      customers_url: https://raw.githubusercontent.com/alexellis/derek/master/.CUSTOMERS
      validate_hmac: false
      validate_customers: true
      secret_path: /var/openfaas/secrets/ # use /run/secrets/ for older OpenFaaS versions
```
image

## updated tests to cover handling of newlines

image

image

image

image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kolyshkin** [comment]
@rgee0 thanks for your work! I am interested if you tried running `Test_getCommandValue` before your commit. I mean, it makes sense to check that the test fails before and passes after a fix.

**Comment by alexellis** [comment]
@kolyshkin the tests I believe are run through CI and Richard is known for his attention to detail and unit testing. Do we have some issues with the CI not running all tests for all packages?

I made a change for this recently, not sure if it's related?

Alex

**Comment by alexellis** [comment]
@rgee0 FYI I've been making major structural changes to the Derek README. Please can you revert your changes to README.md and apply them to the user guide? I'll go ahead and merge after that then bump the version.

Alex

**Comment by rgee0** [comment]
rebased

**Pull request merged**
